

async def as_external_message_payload(): ...

async def as_internal_message_payload(): ... 

async def as_external_message(): ...

async def as_internal_message_payload(): ...

async def as_state_init(): ...

